/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kirnmvptguicplaqiimi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtpcm5tdnB0Z3VpY3BsYXFpaW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxNzQwNzksImV4cCI6MjEwMjc1MDA3OX0.MkpoJk-xEHUqIcDcOuMMygPhVy-0WRW-ORT7wqNSKAc"